// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi5._0.Data;

namespace WebApi5._0.Migrations
{
    [DbContext(typeof(myDbContext))]
    [Migration("20250228035620_AddUserData")]
    partial class AddUserData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi5._0.Data.dbCategory", b =>
                {
                    b.Property<int>("CategoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoriesName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriesId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbDetailOrder", b =>
                {
                    b.Property<Guid>("goodsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("orderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("dbuseruserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("goodsPrice")
                        .HasColumnType("float");

                    b.Property<byte>("goodsSaleOff")
                        .HasColumnType("tinyint");

                    b.Property<int>("orderNumber")
                        .HasColumnType("int");

                    b.HasKey("goodsId", "orderId");

                    b.HasIndex("dbuseruserId");

                    b.HasIndex("orderId");

                    b.ToTable("DetailOrder");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbGoods", b =>
                {
                    b.Property<Guid>("goodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<string>("goodsCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodsDescribe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("goodsPrice")
                        .HasColumnType("float");

                    b.Property<byte>("goodsSaleOff")
                        .HasColumnType("tinyint");

                    b.HasKey("goodsId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("dbGoods");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbOrders", b =>
                {
                    b.Property<Guid>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("consignee")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("dbuseruserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("deliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("numberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("orStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("orderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("orderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("orderId");

                    b.HasIndex("dbuseruserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbUser", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("decentralization")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userNameCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("dbUsers");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbDetailOrder", b =>
                {
                    b.HasOne("WebApi5._0.Data.dbUser", "dbuser")
                        .WithMany("detailorders")
                        .HasForeignKey("dbuseruserId")
                        .HasConstraintName("FK_DetailOrder_User");

                    b.HasOne("WebApi5._0.Data.dbGoods", "dbgoods")
                        .WithMany("detailorders")
                        .HasForeignKey("goodsId")
                        .HasConstraintName("FK_DetailOrder_Goods")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi5._0.Data.dbOrders", "dborders")
                        .WithMany("detailorders")
                        .HasForeignKey("orderId")
                        .HasConstraintName("FK_DetailOrder_Order")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dbgoods");

                    b.Navigation("dborders");

                    b.Navigation("dbuser");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbGoods", b =>
                {
                    b.HasOne("WebApi5._0.Data.dbCategory", "category")
                        .WithMany("dbgoods")
                        .HasForeignKey("CategoriesId");

                    b.Navigation("category");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbOrders", b =>
                {
                    b.HasOne("WebApi5._0.Data.dbUser", "dbuser")
                        .WithMany("orders")
                        .HasForeignKey("dbuseruserId")
                        .HasConstraintName("FK_Order_User");

                    b.Navigation("dbuser");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbCategory", b =>
                {
                    b.Navigation("dbgoods");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbGoods", b =>
                {
                    b.Navigation("detailorders");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbOrders", b =>
                {
                    b.Navigation("detailorders");
                });

            modelBuilder.Entity("WebApi5._0.Data.dbUser", b =>
                {
                    b.Navigation("detailorders");

                    b.Navigation("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
