// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi5._0.Data;

namespace WebApi5._0.Migrations
{
    [DbContext(typeof(myDbContext))]
    [Migration("20250224145436_AddTableCategories")]
    partial class AddTableCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi5._0.Controllers.Data.dbCategory", b =>
                {
                    b.Property<int>("CategoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoriesName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriesId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WebApi5._0.Controllers.Data.dbGoods", b =>
                {
                    b.Property<Guid>("goodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<string>("goodsCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodsDescribe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("goodsPrice")
                        .HasColumnType("float");

                    b.Property<byte>("goodsSaleOff")
                        .HasColumnType("tinyint");

                    b.HasKey("goodsId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("dbGoods");
                });

            modelBuilder.Entity("WebApi5._0.Controllers.Data.dbGoods", b =>
                {
                    b.HasOne("WebApi5._0.Controllers.Data.dbCategory", "category")
                        .WithMany("dbgoods")
                        .HasForeignKey("CategoriesId");

                    b.Navigation("category");
                });

            modelBuilder.Entity("WebApi5._0.Controllers.Data.dbCategory", b =>
                {
                    b.Navigation("dbgoods");
                });
#pragma warning restore 612, 618
        }
    }
}
