// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi5._0.Data;

namespace WebApi5._0.Migrations
{
    [DbContext(typeof(myDbContext))]
    [Migration("20250224143741_DataBaseInitial")]
    partial class DataBaseInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi5._0.Controllers.Data.dbGoods", b =>
                {
                    b.Property<Guid>("goodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("goodsCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodsDescribe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goodsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("goodsPrice")
                        .HasColumnType("float");

                    b.Property<byte>("goodsSaleOff")
                        .HasColumnType("tinyint");

                    b.HasKey("goodsId");

                    b.ToTable("dbGoods");
                });
#pragma warning restore 612, 618
        }
    }
}
